spring:
  application:
    name: punto-red-backend
  datasource:
    url: jdbc:mysql://158.220.99.85:3306/punto_red
    username: puntored_user
    password: Pr@PuntoRed2025
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

server:
  port: 9000
  servlet:
    context-path: /api

# Configuración Punto Red
punto-red:
  webclient:
    url: https://sandbox-v1.portalventas.net
    username: test
    password: "/1,52HW+s.jg"
    connectTimeOut: 10
    readTimeOut: 30
    postProcessingPricingPath: /v1/pricing

# Configuración FusionAuth
fusion-auth:
  webclient:
    url: http://158.220.99.85:9011
    authorization: Lb3Ouo5CGfIJjevorClMq7Kc0l3lBjEZ_Ii3c-hJiLP5AEQPDRdw7TWy
    applicationId: 5359f6f6-42ef-43a5-a840-29d0e8b961fa
    connectTimeOut: 10
    readTimeOut: 30
  jwks-url: http://158.220.99.85:9011/.well-known/jwks.json